### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by elros88** [Bacon2D/Bacon2D#147]
When trying to compile on MAcOSX with Qt 15.5.2, it gives me this error for the tilelib
Undefined symbols for architecture x86_64:
  "_deflate", referenced from:
      Tiled::compress(QByteArray const&, Tiled::CompressionMethod) in compression.o
  "_deflateEnd", referenced from:
      Tiled::compress(QByteArray const&, Tiled::CompressionMethod) in compression.o
  "_deflateInit2_", referenced from:
      Tiled::compress(QByteArray const&, Tiled::CompressionMethod) in compression.o
  "_inflate", referenced from:
      Tiled::decompress(QByteArray const&, int) in compression.o
  "_inflateEnd", referenced from:
      Tiled::decompress(QByteArray const&, int) in compression.o
  "_inflateInit2_", referenced from:
      Tiled::decompress(QByteArray const&, int) in compression.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [qml/Bacon2D/libbacon2dplugin.dylib] Error 1
make: *** [sub-src-make_first] Error 2
